### ISSUE TITLE
Linking External ITK and VTK doesn't force rebuild after change

### ISSUE THREAD

**Issue by kayarre** [vmtk/vmtk#248] opened 2018-03-01 18:12 UTC
when linking external ITK and  VTK making changes to vmtk doesn't force a rebuild

have to ` make clean; make`

**Comment by rlizzo** [comment] 2018-04-10 00:14
This is a behavior i've been annoyed by for a long time. I don't really understand it since the vmtkScripts/cmakeLists.txt file install logic should identify the python files which have changed and automatically reinstall them when running `make`. The relevant code is here:

https://github.com/vmtk/vmtk/blob/0be71a3546c3f0d063ee6ae5f033798f393e10d5/vmtkScripts/CMakeLists.txt#L169-L171

@lantiga, any ideas on this one?

**Comment by rlizzo** [comment] 2018-04-11 16:26
It gets wierd with the C++ parts. Ive been playing around with it a bit but
have noticed some odd behavior that (only sometimes) if you only edit the
header files it won't find anything to update. It seems to find changes
every time with the .cxx files.

However, updates to the python scripts never update on edits without
running "clean" first.

The forums haven't been particularly helpful here either. This sort of
thing has been reported to occur when you use a "FILE ( GLOB foo)"
statement, since apparently that is only executed at generation time. The
general advice is to add a cmake_custom_command to pick up changes, but
it's not really apparent how to this would solve the problem or be relevant
to our build system. I'm working on a c++ feature addition now, so maybe
ill stumble across a solution to it. If not I'll probably post on the CMake
mailing list to see if I can get any other info.

**Comment by rlizzo** [comment] 2018-04-12 00:26
Actually, I was wrong, the C++ side only rebuilds if there is a compilation error. otherwise you have to `make clean` and `make` in order for it to pick up changes.

**Comment by lassoan** [comment] 2018-04-12 00:40
Do you expect running `make` to install Python files? For installation, you need to run `make install`. If you need to copy files during build step then you need to add a custom target for that.

**Comment by lassoan** [comment] 2018-04-12 03:11
I had a look at the code. Probably the issue is that you copy many files using CONFIGURE_FILE.

**Comment by rlizzo** [comment] 2018-04-13 23:59
Wow. this was actually a really tricky behavior to understand since it's actually not an issue with the CMakeLists.txt files, but with how we use VMTK as a superbuild project. However, it's fixed by specifying a single parameter :) 

PR: https://github.com/vmtk/vmtk/pull/267.

From the last paragraph of page 17 in [this article](https://blog.kitware.com/wp-content/uploads/2016/01/kitware_quarterly1009.pdf). 

> One drawback, however, is ExternalProject’s lack of full dependency analysis. Changes in header files of an external project may not cause an incremental rebuild of the affected sources that depend on those headers. This is because the build step might not re-run. A complete list of header files is not given as input to the build step, so there is nothing to indicate that the build step should re-run. This problem can be circumvented by touching or deleting a build step’s corresponding stamp file which will force it to run.

Newer versions of CMake (our minimum required is 3.3) added an ALWAYS_BUILD option which takes care of it. Thanks for all the help everyone!

**Comment by rlizzo** [comment] 2018-04-14 00:35
Btw, thanks for the feedback @lassoan, I don't think I would have realized it was a SuperBuild issue unless you pointed out that a make and install steps don't typically happen at the same time!

**Comment by lassoan** [comment] 2018-04-14 04:25
I'm glad you've found a solution.

In most of our projects, we end up enabling BUILD_ALWAYS flag for all external projects (ITK, VTK, etc.) as well, otherwise when you update version of these libraries, you would need to manually rebuild several projects. Of course, the drawback is that this makes top-level builds take longer. However, you can still build only a specific projects by running make in that project's folder instead of running make the top-level binary folder.

**Comment by rlizzo** [comment] 2018-04-14 14:47
Probably not a bad idea. At the very least I'll add in some documentation about it. We need to document the build process because it's rather strange :)

**Closed by rlizzo** 2018-04-14 14:47 UTC
